services:
  db:
    image: pgvector/pgvector:pg16
    container_name: agente_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: agente_inteligente
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_init:/docker-entrypoint-initdb.d
    networks:
      - agente_net

networks:
  agente_net:
    driver: bridge